name: generate ascii artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Cowsay ascii script
              run: |
                chmod +x Scripts/ascii-artwork.sh
                ./Scripts/ascii-artwork.sh